name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.5
        with: 
          working-directory: './'
          doxyfile-path: 'docs/Doxygen'
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
